### ISSUE TITLE
1.19 ？

### ISSUE THREAD

**Issue by Yexiaowei11** [OreCruncher/DynamicSurroundingsFabric#29]
When to update the 1.19 version

**Comment by jmattingley23** [comment]
I made a pull request to update to 1.19 here, there's download links inside: https://github.com/OreCruncher/DynamicSurroundingsFabric/pull/27

**Comment by OreCruncher** [comment]
Currently no plans to release for 1.19.  I am focusing on 1.20.4+ given time constraints.

**Comment by PlayfulPiano** [comment]
are there no plans to using the already made pull requests as backported versions for 1.18/1.19 if the PRs are ok with it?

**Comment by OreCruncher** [comment]
Right now I have limited amounts of time to work on the mod as well as providing support.  Recently I have been making significant amount of internal changes so that I can eventually get to the point of building the mod for multiple loaders (like Neoforge).   Once I clear that hurdle I can see how things sit.

**Comment by PlayfulPiano** [comment]
That makes sense for official backports / loader support, but for the time being just for accessibility / publicity sake it might be worthwhile to publicize the already made PR that have 1.18/1.19 functionality just so people won't need to try and find them through github/need the knowledge to self build .jar files.
