### ISSUE TITLE
[1.20.1] [Sinytra] Conflict w/ModernFix registry modifications

### ISSUE THREAD

**Issue by liangmoe** [OreCruncher/DynamicSurroundingsFabric#68]
The know missing feature: bow pulling sound and steam columns effect

0.2.2 steam columns:
![2024-01-27_04 19 45](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/135343248/e871c2e6-a85f-4683-ad30-c0ac00d91be2)

0.3.0 steam colums:
![2024-01-27_04 15 36](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/135343248/9f543952-031a-4317-afb0-7c10a6062426)

Fabric side 0.3.0 steam colums:
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/135343248/bea3fb53-abf2-4481-9e23-fe0789e3aa36)

0.2.2 latest.log: https://mclo.gs/MLju2jw

0.3.0 latest.log: https://mclo.gs/AHuOgtu

**Comment by OreCruncher** [comment]
What modpack?  I just loaded up my Forge test instance and its working. Also, is this integrated server or connected to a remote server?  Lastly, try the command /dsreload and see if it fixes it.

**Comment by OreCruncher** [comment]
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/6394607/4dd13019-1d09-4ae1-ac1e-51f5ccf02595)

It looks like something is interfering with my scanning of my mods resources. Going to need the mod pack.

**Comment by liangmoe** [comment]
Cant drop mrpack here, can i contact you on discord? modrinth page's discord link is invaild

**Comment by OreCruncher** [comment]
yeah - ping me directly on discord.

**Comment by liangmoe** [comment]
ive send friend request to you, cand find the working discord link and also cant find you in connector's discord

**Comment by OreCruncher** [comment]
Ok - looks to be a conflict with ModernFix.  I change the method of how I scan for resource pack resources to a different API in the ResourceManager.  You can turn off the resource pack performance tweaks of ModernFix by editing the modernfix-mixins.properties file and add "mixin.perf.resourcepacks=false" to the bottom.

**Comment by OreCruncher** [comment]
I do not see this issue with ModernFix for Fabric on 1.20.4.

**Comment by liangmoe** [comment]
I do not see the issue with modernfix on fabric 1.20.1 either

**Comment by OreCruncher** [comment]
OK - beat my head on this one quite a bit.  I think it is specifically ModernFix in a forge setup with Sinytra. Only way to work around it is to disable the perf for resources for ModernFix. On the plus side I made resource loading is much faster. With ATM9 Forge using Sinytra and my mod loading was about 70 seconds.  Got it down to about 300 or so milliseconds.

**Comment by embeddedt** [comment]
Could you explain what you changed about resource access in 0.3.0 and how it works now? There is a fix coming in 5.13 for some resource pack issues and I want to ensure this will also be addressed.

**Comment by OreCruncher** [comment]
It was the method for resource access. My mod scans loaded mods and resource packs looking the assets it needs. I made a tweak to take into account external resource packs. Though I don't know for certain, I think there is logic somewhere (at what layer/aspect that I do not know) that makes an assumption about how a given mod would interact with resource packs.

Regarding tags, these things live in the /data path of a resource pack. In 0.3.0 I moved my tagging into /assets. Minecraft will not load my tag information since it is not in /data, which is what I want - I am a client-side mod after all. I have special scanning logic that will look in /assets and /data for tag information and initialize its internal tag cache. This is important if a user uses fabric + clientside mods to connect with a Vanilla server. The server has no notion of forge or c tags, so my tag cache has to do the crawl through client side /asset and /data folders looking for the tag information.

Link to the code that I am currently using to scan for pack resources:  https://github.com/OreCruncher/DynamicSurroundingsFabric/blob/ac451d1376e3b88f98f73404da7fd235736e57fe/src/main/java/org/orecruncher/dsurround/lib/resources/ModConfigResourceFinder.java#L23

One other thing I noticed when scanning for sounds.json, when ModernFix resource mixin was enabled it would only return "minecraft:sounds.json". When disabled it gave me all the mods that have sounds.json files. Relevant code location: https://github.com/OreCruncher/DynamicSurroundingsFabric/blob/ac451d1376e3b88f98f73404da7fd235736e57fe/src/main/java/org/orecruncher/dsurround/lib/resources/ClientResourceFinder.java#L32.

**Comment by embeddedt** [comment]
Thanks for the info & hints.

Can someone confirm that https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20/Package.zip works without requiring `mixin.perf.resourcepacks` to be disabled?

**Comment by liangmoe** [comment]
> Thanks for the info & hints.
> 
> Can someone confirm that https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20/Package.zip works without requiring `mixin.perf.resourcepacks` to be disabled?

Can confirm that

**Comment by OreCruncher** [comment]
@embeddedt Yep - looks good.  I dropped the Forge version into ATM9 w/Sinytra and my mod and it scans things correctly.

**Comment by OreCruncher** [comment]
Posted 0.3.1 versions to CurseForge/GitHub. Though there is no specific fix for this particular issue I did rework asset handling to improve performance. Tested the fixes with ATM9 and the fixes made to ModernFix.
