### ISSUE TITLE
[1.20.x] No elytra sounds when flying

### ISSUE THREAD

**Issue by MotMomet** [OreCruncher/DynamicSurroundingsFabric#80]
I just noticed while playing there is no sounds with elytra. I tried to open minecraft without dsurround and then i was able the hear the elytra sounds. Then i thought is there a mod that makes this when both installed? well no i tried to using only dsurround and fabric api in my modpack but there is still no elytra sounds. Is there a quick way to fix this? like removing something from mod resourcepack like sound or editing config files?

**Comment by MotMomet** [comment]
Thanks for the reply and informations. And about modpack its a custom one i made. If you still need it i can upload for you.
I'll try to do what you said on EDIT3 tomorrow, also if i do the EDIT3, is it going to affect my game experience too much? or is it like going to disable some of features?

**Comment by OreCruncher** [comment]
No, I don't need the modpack at this point.  I was able to identify the issue testing in one of my test environments. As for turning of sound pruning it shouldn't affect game experience. I added this feature because sometimes mods will cause sounds that are outside of hearing range, and depending on the quantity it could impact client-side performance.

**Comment by OreCruncher** [comment]
Pushed update to CurseForge and Modrinth.  CurseForge is dragging its feet per usual.
